export enum StatusError {
  NOT_FOUND = 'NOT_FOUND',
  NOT_EXISTS = 'NOT_EXISTS',
  INVALID = 'INVALID',
  REPOSITORY_ERROR = 'REPOSITORY_ERROR',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
